version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app/
hooks:
  AfterInstall:
    - location: scripts/before-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/application-start.sh
      runas: root
      timeout: 60